theme: jekyll-theme-slate
title: Sentiment Analysis in Financial News
description: This project attempts to create ML models to predict sentiments in financial news through the use of convolutional neural network and logistic regression.
